# Generated by Django 4.2.7 on 2023-11-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('designer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designer_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'designer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255, unique=True)),
                ('published_year', models.IntegerField()),
                ('min_player', models.IntegerField()),
                ('max_player', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('min_time', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('is_cooperative', models.IntegerField()),
                ('num_review', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('std_dev_rating', models.FloatField()),
                ('rated_complexity', models.FloatField(blank=True, null=True)),
                ('rated_language_dependency', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gameitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameMechanic',
            fields=[
                ('mechanic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mechanic_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'game_mechanic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'game_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('num_games_published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameItemDesigner',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.gameitem')),
            ],
            options={
                'db_table': 'gameitem_designer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameItemGameMechanic',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.gameitem')),
            ],
            options={
                'db_table': 'gameitem_game_mechanic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameItemGameType',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.gameitem')),
            ],
            options={
                'db_table': 'gameitem_game_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameItemPublisher',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.gameitem')),
            ],
            options={
                'db_table': 'gameitem_publisher',
                'managed': False,
            },
        ),
    ]
