# Generated by Django 4.2.7 on 2023-12-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('game_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255, unique=True)),
                ('published_year', models.IntegerField()),
                ('min_player', models.IntegerField()),
                ('max_player', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('min_time', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('is_cooperative', models.IntegerField()),
                ('num_review', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('std_dev_rating', models.FloatField()),
                ('rated_complexity', models.FloatField(blank=True, null=True)),
                ('rated_language_dependency', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gameitem',
                'managed': True,
            },
        ),
    ]
