# Generated by Django 4.2.7 on 2023-12-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
